### PR TITLE
Don't run wsimport when generated sources are upToDate.

### PR DESCRIPTION
**Pull request by kfowler**
Patch to prevent wsimport from running on every build. Only run wsimport when sources (wsdl, bindings) are newer than generated (settings.dest *\* .java) files.

### CODE REVIEW

**Comment by bancek** [comment]
Thank you for your contribution.

**Comment by kfowler** [comment]
Hi Luka,

Can you please push the latest sbt-jaxws to maven central?

I'm trying to get some code checked-in that relies on it.

Thanks!

Kevin Fowler
kfowler@esterdome.com

**Comment by bancek** [comment]
I just released `0.2`.

**Comment by kfowler** [comment]
Great. Thank you!

—Kevin

**Comment by kfowler** [comment]
Hi Luka,

How do the artifacts get built & deployed to maven central?

Let me know if there's anything I can do to help.

Thanks,

Kevin

**Comment by bancek** [comment]
I've released it to Sonatype OSS. It will take some time to sync with Maven Central.

https://oss.sonatype.org/content/repositories/releases/net/koofr/sbt-jaxws_2.10_0.13/0.2/sbt-jaxws-0.2.pom

**Comment by bancek** [comment]
http://www.scala-sbt.org/release/docs/Using-Sonatype.html

**Comment by bancek** [comment]
It is available on Maven.

https://repo1.maven.org/maven2/net/koofr/sbt-jaxws_2.10_0.13/0.2/sbt-jaxws-0.2.pom

**Comment by kfowler** [comment]
Awesome. Thanks & have a good weekend.

—Kevin

**Pull request merged**
